name: Release

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace'
        required: true
        default: 'fe'
        type: choice
        options:
          - fe
          - be
      build_mode:
        description: 'Build Mode (patch | minor | major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config user.name "mt-ci gh-action"
          git config user.email "mt-ci@gh-action.none"
          git config advice.addIgnoredFile false
          git config advice.detachedHead false

      - name: Verify workspace
        run: |
          echo "workspace: ${{ github.event.inputs.workspace }}"

      - name: Verify build_mode
        run: |
          echo "build_mode: ${{ github.event.inputs.build_mode }}"

      - name: Install dependencies and build 🔧
        run: |
          npm install -g pnpm
          pnpm install

      - name: Versioning application artifact
        run: |
          WORKSPACE=${{ github.event.inputs.workspace }}
          RELEASE_MODE=${{ github.event.inputs.build_mode }}
          pnpm --filter ./packages/$WORKSPACE version $RELEASE_MODE

      - name: Publish package on NPM 📦
        run: |
          WORKSPACE=${{ github.event.inputs.workspace }}
          pnpm release:$WORKSPACE
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - name: Patch latest version to Git
        run: |
          WORKSPACE=${{ github.event.inputs.workspace }}
          VERSION=$(jq -r .version ./packages/$WORKSPACE/package.json)
          COMMIT_MESSAGE="[build]: upgrade $WORKSPACE@$VERSION"
          git fetch
          git checkout main
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push origin main
